// Code generated by ent, DO NOT EDIT.

package feature

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the feature type in the database.
	Label = "feature"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFeatureName holds the string denoting the featurename field in the database.
	FieldFeatureName = "feature_name"
	// FieldFeatureUrl holds the string denoting the featureurl field in the database.
	FieldFeatureUrl = "feature_url"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// Table holds the table name of the feature in the database.
	Table = "features"
	// RoleTable is the table that holds the role relation/edge. The primary key declared below.
	RoleTable = "role_feature"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
)

// Columns holds all SQL columns for feature fields.
var Columns = []string{
	FieldID,
	FieldFeatureName,
	FieldFeatureUrl,
}

var (
	// RolePrimaryKey and RoleColumn2 are the table columns denoting the
	// primary key for the role relation (M2M).
	RolePrimaryKey = []string{"role_id", "feature_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Feature queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFeatureName orders the results by the featureName field.
func ByFeatureName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatureName, opts...).ToFunc()
}

// ByFeatureUrl orders the results by the featureUrl field.
func ByFeatureUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatureUrl, opts...).ToFunc()
}

// ByRoleCount orders the results by role count.
func ByRoleCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoleStep(), opts...)
	}
}

// ByRole orders the results by role terms.
func ByRole(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoleStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRoleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, RoleTable, RolePrimaryKey...),
	)
}
