// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Feature is the predicate function for feature builders.
type Feature func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
